version: "2.2"
services:
  web:
    container_name: web
    build:
      context: .
    image: smallflatworld
    restart: always
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
