baseURL = "http://smallflatworld.com"
languageCode = "en-us"
title = "Small flat world"
theme = "freelancer"

[params]
  tagLine = "Tag line to be included here"
  homePosts = 3
  homeProjects = 3

  aboutLeft = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec velit eu nisl sollicitudin volutpat. Vestibulum vel felis a lorem lobortis lobortis ac in libero. Nunc eget dolor non augue ultricies iaculis."
  aboutRight = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec velit eu nisl sollicitudin volutpat. Vestibulum vel felis a lorem lobortis lobortis ac in libero. Nunc eget dolor non augue ultricies iaculis"

# [params.location]
#   lineOne = "Made in Canada"
#   lineTwo = "With a Brazilian soul" 

[params.sbform]
      token = ""

[params.homebutton]
  text = "Play"
  link = "play" 
  icon = "fa-play"

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10