name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.13.2

    - name: Install dependencies
      working-directory: ./web
      run: npm ci

    - name: Setup web version basedon package.json version
      working-directory: ./web
      run: ./node_modules/.bin/hbs --data package.json src/app/version.hbs --stdout > src/app/version.ts

    - name: Build the Angular app
      working-directory: ./web
      run: ./node_modules/.bin/ng build --configuration production --output-path=dist --base-href /smallflatworld/play/
      run: pwd
      run: ls -alh dist

    - name: Debug after build
      working-directory: ./web
      run: pwd && ls -alh dist

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/dist
        destination_dir: play