name: CI
on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1 
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --prod --output-path=dist 

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages 
        folder: ./web/dist
        token: ${{ secrets.GITHUB_TOKEN }} 
